In [1]:
from sklearn.datasets import load_files
import os

In [20]:
%%time
train_reviews = load_files('/Users/maksn_000/Desktop/aclImdb/train/')

Wall time: 6.22 s


In [19]:
%%time
test_reviews = load_files('/Users/maksn_000/Desktop/aclImdb/test/')

Wall time: 2.05 s


In [6]:
len(train_reviews.data)

25000

In [5]:
len(train_reviews.data)

25000

In [37]:
train_reviews.data[4]

b'If you want Scream or anything like the big-studio horror product that we get forced on us these days don\'t bother. This well-written film kept me up thinking about all it had to say. Importance of myth in our lives to make it make sense, how children interpret the world (and the violence in it), our ransacking of the environment and ignorance of its history and legends.. all here, but not flatly on the surface. You could technically call it a "monster movie" even though the Wendigo does not take physical form until the end, and then it\'s even up to you and your beliefs as to what\'s happening with the legendary spirit/beast. Some standard thriller elements for those looking just for the basics and the film never bores, though in fact the less you see of the creature, the better. Fessenden successfully continues George Romero\'s tradition of using the genre as parable and as a discussion forum while still keeping us creeped out.'

In [38]:
train_reviews.target[4] # good

1

In [23]:
train_reviews.data[1]

b"Amount of disappointment I am getting these days seeing movies like Partner, Jhoom Barabar and now, Heyy Babyy is gonna end my habit of seeing first day shows.<br /><br />The movie is an utter disappointment because it had the potential to become a laugh riot only if the d\xc3\xa9butant director, Sajid Khan hadn't tried too many things. Only saving grace in the movie were the last thirty minutes, which were seriously funny elsewhere the movie fails miserably. First half was desperately been tried to look funny but wasn't. Next 45 minutes were emotional and looked totally artificial and illogical.<br /><br />OK, when you are out for a movie like this you don't expect much logic but all the flaws tend to appear when you don't enjoy the movie and thats the case with Heyy Babyy. Acting is good but thats not enough to keep one interested.<br /><br />For the positives, you can take hot actresses, last 30 minutes, some comic scenes, good acting by the lead cast and the baby. Only problem is

In [30]:
train_reviews.target[1] # bad

2

In [28]:
test_reviews.data[0]

b"Don't hate Heather Graham because she's beautiful, hate her because she's fun to watch in this movie. Like the hip clothing and funky surroundings, the actors in this flick work well together. Casey Affleck is hysterical and Heather Graham literally lights up the screen. The minor characters - Goran Visnjic {sigh} and Patricia Velazquez are as TALENTED as they are gorgeous. Congratulations Miramax & Director Lisa Krueger!"

In [40]:
test_reviews.target[0] # good

1

In [41]:
test_reviews.data[1]

b'I don\'t know how this movie has received so many positive comments. One can call it "artistic" and "beautifully filmed", but those things don\'t make up for the empty plot that was filled with sexual innuendos. I wish I had not wasted my time to watch this movie. Rather than being biographical, it was a poor excuse for promoting strange and lewd behavior. It was just another Hollywood attempt to convince us that that kind of life is normal and OK. From the very beginning I asked my self what was the point of this movie,and I continued watching, hoping that it would change and was quite disappointed that it continued in the same vein. I am so glad I did not spend the money to see this in a theater!'

In [42]:
test_reviews.target[1] # bad

0

BOW - Bag of Words

In [49]:
import numpy as np
import pandas as pd
from scipy.sparse import csr_matrix

In [47]:
a = np.zeros([5,5])
a[0,3] = 1
a[4,4] = 6
a[2,2] = 5
a[3,1] = 4
a[3,2] = 2
a[1,1] = 7

In [48]:
a

array([[0., 0., 0., 1., 0.],
       [0., 7., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 4., 2., 0., 0.],
       [0., 0., 0., 0., 6.]])

In [51]:
pd.DataFrame(a, columns=['apple', 'wax', 'sadness', 'luck', 'girl'])

apple  wax  sadness  luck  girl
0    0.0  0.0      0.0   1.0   0.0
1    0.0  7.0      0.0   0.0   0.0
2    0.0  0.0      5.0   0.0   0.0
3    0.0  4.0      2.0   0.0   0.0
4    0.0  0.0      0.0   0.0   6.0

In [52]:
 b = csr_matrix(a)

In [53]:
b

<5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [56]:
b.todense()

matrix([[0., 0., 0., 1., 0.],
        [0., 7., 0., 0., 0.],
        [0., 0., 5., 0., 0.],
        [0., 4., 2., 0., 0.],
        [0., 0., 0., 0., 6.]])

In [58]:
b.nonzero()

(array([0, 1, 2, 3, 3, 4], dtype=int32),
 array([3, 1, 2, 1, 2, 4], dtype=int32))

In [59]:
b.data

array([1., 7., 5., 4., 2., 6.])

In [60]:
from sklearn.feature_extraction.text import CountVectorizer

In [92]:
cv = CountVectorizer(ngram_range=(1,2))
X_train_sparse = cv.fit_transform(train_reviews.data)

In [93]:
len(cv.vocabulary_)

3334041

In [94]:
%%time
X_test_sparse = cv.transform(test_reviews.data)

Wall time: 12.2 s


In [95]:
X_train_sparse.shape, X_test_sparse.shape 

((75000, 3334041), (25000, 3334041))

In [96]:
X_train_sparse

<75000x3334041 sparse matrix of type '<class 'numpy.int64'>'
	with 26350221 stored elements in Compressed Sparse Row format>

In [97]:
26350221 / (75000 * 3334041)

0.00010537851214187228

In [73]:
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.metrics import accuracy_score

In [74]:
y_train, y_test = train_reviews.target, test_reviews.target

In [75]:
np.bincount(y_train), np.bincount(y_test)

(array([12500, 12500, 50000], dtype=int64), array([12500, 12500], dtype=int64))

In [84]:
logit = LogisticRegression(random_state=17, n_jobs=-1)
sgd_logit = SGDClassifier(max_iter=13, random_state=17, n_jobs=-1)

In [79]:
10 ** 6 / X_train_sparse.shape[0]

13.333333333333334

In [87]:
%%time
logit.fit(X_train_sparse, y_train)

Wall time: 21.7 s


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=-1, penalty='l2', random_state=17,
                   solver='lbfgs', tol=0.0001, verbose=0, warm_start=False)

In [98]:
%%time
sgd_logit.fit(X_train_sparse, y_train)

Wall time: 6.22 s


C:\Users\maksn_000\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)


SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge', max_iter=13,
              n_iter_no_change=5, n_jobs=-1, penalty='l2', power_t=0.5,
              random_state=17, shuffle=True, tol=0.001, validation_fraction=0.1,
              verbose=0, warm_start=False)

In [88]:
accuracy_score(y_test, logit.predict(X_test_sparse))

0.1324

In [99]:
accuracy_score(y_test, sgd_logit.predict(X_test_sparse))

0.18028

In [91]:
visualize_coefficients(logit, cv.get_feature_names())

NameError: name 'visualize_coefficients' is not defined

In [5]:
hash('be very nice') % 10 ** 6

992200

In [7]:
2 ** 18

262144